//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INetApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INetApp.Resources.Literales", typeof(Literales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes marcadas .
        /// </summary>
        internal static string action_favorites {
            get {
                return ResourceManager.GetString("action_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación y Conocimiento.
        /// </summary>
        internal static string action_formation {
            get {
                return ResourceManager.GetString("action_formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string action_logout {
            get {
                return ResourceManager.GetString("action_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de entrada.
        /// </summary>
        internal static string action_messages {
            get {
                return ResourceManager.GetString("action_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de trabajo.
        /// </summary>
        internal static string action_parts {
            get {
                return ResourceManager.GetString("action_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de acceso - Lector QR.
        /// </summary>
        internal static string action_qr {
            get {
                return ResourceManager.GetString("action_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        internal static string action_search {
            get {
                return ResourceManager.GetString("action_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Accceso - Lector Qr.
        /// </summary>
        internal static string activity_title_lector {
            get {
                return ResourceManager.GetString("activity_title_lector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string activity_title_main {
            get {
                return ResourceManager.GetString("activity_title_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de entrada.
        /// </summary>
        internal static string activity_title_message_category {
            get {
                return ResourceManager.GetString("activity_title_message_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de solicitud.
        /// </summary>
        internal static string activity_title_message_details {
            get {
                return ResourceManager.GetString("activity_title_message_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de solicitudes.
        /// </summary>
        internal static string activity_title_message_list {
            get {
                return ResourceManager.GetString("activity_title_message_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible resgistrar el servicio de Notificaciones.
        /// </summary>
        internal static string alrt_noregisternotificationservice {
            get {
                return ResourceManager.GetString("alrt_noregisternotificationservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InetApp.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        internal static string btn_reintentar {
            get {
                return ResourceManager.GetString("btn_reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmar.
        /// </summary>
        internal static string btn_sign {
            get {
                return ResourceManager.GetString("btn_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string btn_text_accept {
            get {
                return ResourceManager.GetString("btn_text_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APROBAR.
        /// </summary>
        internal static string btn_text_approve {
            get {
                return ResourceManager.GetString("btn_text_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string btn_text_login {
            get {
                return ResourceManager.GetString("btn_text_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECHAZAR.
        /// </summary>
        internal static string btn_text_refuse {
            get {
                return ResourceManager.GetString("btn_text_refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        internal static string btn_text_retry {
            get {
                return ResourceManager.GetString("btn_text_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar parte de la semana anterior.
        /// </summary>
        internal static string copy_last_week {
            get {
                return ResourceManager.GetString("copy_last_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.ineco.android.master.
        /// </summary>
        internal static string credenciales {
            get {
                return ResourceManager.GetString("credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una nueva versión de la aplicación.
        /// </summary>
        internal static string dialog_approve_install {
            get {
                return ResourceManager.GetString("dialog_approve_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea aprobar la solicitud?.
        /// </summary>
        internal static string dialog_approve_message {
            get {
                return ResourceManager.GetString("dialog_approve_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene algunas solicitudes marcadas. ¿Desea aprobarlas?.
        /// </summary>
        internal static string dialog_approve_messages {
            get {
                return ResourceManager.GetString("dialog_approve_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        internal static string dialog_approve_positive {
            get {
                return ResourceManager.GetString("dialog_approve_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar.
        /// </summary>
        internal static string dialog_approve_positive_install {
            get {
                return ResourceManager.GetString("dialog_approve_positive_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca mínimo 4 carácteres.
        /// </summary>
        internal static string dialog_approve_search {
            get {
                return ResourceManager.GetString("dialog_approve_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar solicitud.
        /// </summary>
        internal static string dialog_approve_title {
            get {
                return ResourceManager.GetString("dialog_approve_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string dialog_approve_title_search {
            get {
                return ResourceManager.GetString("dialog_approve_title_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso correcto..
        /// </summary>
        internal static string dialog_correct_access {
            get {
                return ResourceManager.GetString("dialog_correct_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las horas imputadas en un día superan el máximo permitido.
        /// </summary>
        internal static string dialog_pend_save {
            get {
                return ResourceManager.GetString("dialog_pend_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea rechazar la solicitud?.
        /// </summary>
        internal static string dialog_refuse_message {
            get {
                return ResourceManager.GetString("dialog_refuse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene algunas solicitudes marcadas. ¿Desea rechazarlas?.
        /// </summary>
        internal static string dialog_refuse_messages {
            get {
                return ResourceManager.GetString("dialog_refuse_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string dialog_refuse_positive {
            get {
                return ResourceManager.GetString("dialog_refuse_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        internal static string dialog_refuse_reason {
            get {
                return ResourceManager.GetString("dialog_refuse_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe informar el motivo de rechazo.
        /// </summary>
        internal static string dialog_refuse_text {
            get {
                return ResourceManager.GetString("dialog_refuse_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar solicitud.
        /// </summary>
        internal static string dialog_refuse_title {
            get {
                return ResourceManager.GetString("dialog_refuse_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string dialog_search_positive {
            get {
                return ResourceManager.GetString("dialog_search_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar menú.
        /// </summary>
        internal static string drawer_close {
            get {
                return ResourceManager.GetString("drawer_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir menú.
        /// </summary>
        internal static string drawer_open {
            get {
                return ResourceManager.GetString("drawer_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay elementos en la bandeja de entrada.
        /// </summary>
        internal static string empty_categories {
            get {
                return ResourceManager.GetString("empty_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen solicitudes.
        /// </summary>
        internal static string empty_messages {
            get {
                return ResourceManager.GetString("empty_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error en la aplicación.
        /// </summary>
        internal static string exception_message_generic {
            get {
                return ResourceManager.GetString("exception_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrectos. Por favor inténtelo de nuevo..
        /// </summary>
        internal static string exception_message_login {
            get {
                return ResourceManager.GetString("exception_message_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible obtener datos de la solicitud. Compruebe su conexión a internet.
        /// </summary>
        internal static string exception_message_message_not_found {
            get {
                return ResourceManager.GetString("exception_message_message_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión a internet parece estar desactivada.
        /// </summary>
        internal static string exception_message_no_connection {
            get {
                return ResourceManager.GetString("exception_message_no_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible obtener datos de usuario. Compruebe su conexión a internet.
        /// </summary>
        internal static string exception_message_user_not_found {
            get {
                return ResourceManager.GetString("exception_message_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string hint_text_email {
            get {
                return ResourceManager.GetString("hint_text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        internal static string hint_text_label {
            get {
                return ResourceManager.GetString("hint_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string hint_text_password {
            get {
                return ResourceManager.GetString("hint_text_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string hint_text_user {
            get {
                return ResourceManager.GetString("hint_text_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info InetApp.
        /// </summary>
        internal static string info_inetapp {
            get {
                return ResourceManager.GetString("info_inetapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string keyapp {
            get {
                return ResourceManager.GetString("keyapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categoryName.
        /// </summary>
        internal static string keycategoryname {
            get {
                return ResourceManager.GetString("keycategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i6KvvUNxz7.
        /// </summary>
        internal static string keyfullnombreuser {
            get {
                return ResourceManager.GetString("keyfullnombreuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IzSkiR0nDz.
        /// </summary>
        internal static string keyfullpassuser {
            get {
                return ResourceManager.GetString("keyfullpassuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreUser.
        /// </summary>
        internal static string keynombreuser {
            get {
                return ResourceManager.GetString("keynombreuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreUsuarioFull.
        /// </summary>
        internal static string keynombreuserfull {
            get {
                return ResourceManager.GetString("keynombreuserfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idApplication.
        /// </summary>
        internal static string keynotidapplication {
            get {
                return ResourceManager.GetString("keynotidapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idSolicitud.
        /// </summary>
        internal static string keynotidsolicitud {
            get {
                return ResourceManager.GetString("keynotidsolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notiExterna.
        /// </summary>
        internal static string keynoTipoMsg {
            get {
                return ResourceManager.GetString("keynoTipoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string keynotmessage {
            get {
                return ResourceManager.GetString("keynotmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numSolicitudes.
        /// </summary>
        internal static string keynotnumsolicitudes {
            get {
                return ResourceManager.GetString("keynotnumsolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string keynottitle {
            get {
                return ResourceManager.GetString("keynottitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string keynoUrlMsg {
            get {
                return ResourceManager.GetString("keynoUrlMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isPermission.
        /// </summary>
        internal static string keyPermission {
            get {
                return ResourceManager.GetString("keyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol.
        /// </summary>
        internal static string keysol {
            get {
                return ResourceManager.GetString("keysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dispone de permisos para acceder a este contenido.
        /// </summary>
        internal static string no_permissions {
            get {
                return ResourceManager.GetString("no_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo abrir la puerta, inténtelo de nuevo más tarde..
        /// </summary>
        internal static string notification_text {
            get {
                return ResourceManager.GetString("notification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo abrir la puerta..
        /// </summary>
        internal static string notification_title {
            get {
                return ResourceManager.GetString("notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña vacia. Por favor inténtelo de nuevo.
        /// </summary>
        internal static string password_empty_error {
            get {
                return ResourceManager.GetString("password_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas pendientes.
        /// </summary>
        internal static string pending_hours {
            get {
                return ResourceManager.GetString("pending_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenRegsitration.
        /// </summary>
        internal static string registratiotoken {
            get {
                return ResourceManager.GetString("registratiotoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todos.
        /// </summary>
        internal static string seleccionartodos {
            get {
                return ResourceManager.GetString("seleccionartodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13164573839.
        /// </summary>
        internal static string sender_id {
            get {
                return ResourceManager.GetString("sender_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista no accesible.
        /// </summary>
        internal static string string_content_description {
            get {
                return ResourceManager.GetString("string_content_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAS.
        /// </summary>
        internal static string tab_text_all {
            get {
                return ResourceManager.GetString("tab_text_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCADAS.
        /// </summary>
        internal static string tab_text_marked {
            get {
                return ResourceManager.GetString("tab_text_marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECTO.
        /// </summary>
        internal static string table_project {
            get {
                return ResourceManager.GetString("table_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. GESTIÓN.
        /// </summary>
        internal static string table_project_management {
            get {
                return ResourceManager.GetString("table_project_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -SELECCIONA PROYECTO-.
        /// </summary>
        internal static string text_combo {
            get {
                return ResourceManager.GetString("text_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicación contrato: {0}.
        /// </summary>
        internal static string text_dedication {
            get {
                return ResourceManager.GetString("text_dedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETALLES.
        /// </summary>
        internal static string text_details {
            get {
                return ResourceManager.GetString("text_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes activar o desactivar las distintas bandejas de solicitudes a través del menú principal:.
        /// </summary>
        internal static string text_info {
            get {
                return ResourceManager.GetString("text_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string text_label {
            get {
                return ResourceManager.GetString("text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situe el código QR en el centro del lector para verificar el acceso:.
        /// </summary>
        internal static string text_lector {
            get {
                return ResourceManager.GetString("text_lector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estas son las Bandejas de solicitudes pendientes disponibles actualmente:.
        /// </summary>
        internal static string text_options {
            get {
                return ResourceManager.GetString("text_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce el ID o Título del proyecto.
        /// </summary>
        internal static string text_proyect_search {
            get {
                return ResourceManager.GetString("text_proyect_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmado.
        /// </summary>
        internal static string text_signed {
            get {
                return ResourceManager.GetString("text_signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validado.
        /// </summary>
        internal static string text_validated {
            get {
                return ResourceManager.GetString("text_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana {0}.
        /// </summary>
        internal static string text_week {
            get {
                return ResourceManager.GetString("text_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud aprobada correctamente.
        /// </summary>
        internal static string toast_approve_message {
            get {
                return ResourceManager.GetString("toast_approve_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible aprobar la solicitud.
        /// </summary>
        internal static string toast_approve_message_error {
            get {
                return ResourceManager.GetString("toast_approve_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes aprobadas correctamente.
        /// </summary>
        internal static string toast_approve_messages {
            get {
                return ResourceManager.GetString("toast_approve_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones guardadas correctamente.
        /// </summary>
        internal static string toast_approve_options {
            get {
                return ResourceManager.GetString("toast_approve_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar iconos.
        /// </summary>
        internal static string toast_error_icons {
            get {
                return ResourceManager.GetString("toast_error_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunos mensajes no han sido aprobados.
        /// </summary>
        internal static string toast_not_all_messages_approved {
            get {
                return ResourceManager.GetString("toast_not_all_messages_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunos mensajes no han sido rechazados.
        /// </summary>
        internal static string toast_not_all_messages_refused {
            get {
                return ResourceManager.GetString("toast_not_all_messages_refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud rechazada correctamente.
        /// </summary>
        internal static string toast_refuse_message {
            get {
                return ResourceManager.GetString("toast_refuse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible rechazar la solicitud.
        /// </summary>
        internal static string toast_refuse_message_error {
            get {
                return ResourceManager.GetString("toast_refuse_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes rechazadas correctamente.
        /// </summary>
        internal static string toast_refuse_messages {
            get {
                return ResourceManager.GetString("toast_refuse_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte guardado correctamente.
        /// </summary>
        internal static string toast_save_parts {
            get {
                return ResourceManager.GetString("toast_save_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte firmado correctamente.
        /// </summary>
        internal static string toast_sign_parts {
            get {
                return ResourceManager.GetString("toast_sign_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas totales.
        /// </summary>
        internal static string total_hours {
            get {
                return ResourceManager.GetString("total_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total horas semana: {0}.
        /// </summary>
        internal static string total_week_hours {
            get {
                return ResourceManager.GetString("total_week_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ineco.com/.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario vacio. Por favor inténtelo de nuevo.
        /// </summary>
        internal static string username_empty_error {
            get {
                return ResourceManager.GetString("username_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión InetApp.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚLTIMA ACTUALIZACIÓN: {0}.
        /// </summary>
        internal static string view_text_last_updated {
            get {
                return ResourceManager.GetString("view_text_last_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar ahora.
        /// </summary>
        internal static string view_text_update_now {
            get {
                return ResourceManager.GetString("view_text_update_now", resourceCulture);
            }
        }
    }
}
