//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INetApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INetApp.Resources.Literales", typeof(Literales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes marcadas .
        /// </summary>
        internal static string action_favorites {
            get {
                return ResourceManager.GetString("action_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formación y Conocimiento.
        /// </summary>
        internal static string action_formation {
            get {
                return ResourceManager.GetString("action_formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string action_logout {
            get {
                return ResourceManager.GetString("action_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandeja de entrada.
        /// </summary>
        internal static string action_messages {
            get {
                return ResourceManager.GetString("action_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partes de trabajo.
        /// </summary>
        internal static string action_parts {
            get {
                return ResourceManager.GetString("action_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de acceso - Lector QR.
        /// </summary>
        internal static string action_qr {
            get {
                return ResourceManager.GetString("action_qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        internal static string action_search {
            get {
                return ResourceManager.GetString("action_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control Accceso - Lector Qr.
        /// </summary>
        internal static string activity_title_lector {
            get {
                return ResourceManager.GetString("activity_title_lector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string activity_title_main {
            get {
                return ResourceManager.GetString("activity_title_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandeja de entrada.
        /// </summary>
        internal static string activity_title_message_category {
            get {
                return ResourceManager.GetString("activity_title_message_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de solicitud.
        /// </summary>
        internal static string activity_title_message_details {
            get {
                return ResourceManager.GetString("activity_title_message_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de solicitudes.
        /// </summary>
        internal static string activity_title_message_list {
            get {
                return ResourceManager.GetString("activity_title_message_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imposible resgistrar el servicio de Notificciones.
        /// </summary>
        internal static string alrt_noregisternotificationservice {
            get {
                return ResourceManager.GetString("alrt_noregisternotificationservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InetApp.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        internal static string btn_reintentar {
            get {
                return ResourceManager.GetString("btn_reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmar.
        /// </summary>
        internal static string btn_sign {
            get {
                return ResourceManager.GetString("btn_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btn_text_accept {
            get {
                return ResourceManager.GetString("btn_text_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APROBAR.
        /// </summary>
        internal static string btn_text_approve {
            get {
                return ResourceManager.GetString("btn_text_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string btn_text_login {
            get {
                return ResourceManager.GetString("btn_text_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECHAZAR.
        /// </summary>
        internal static string btn_text_refuse {
            get {
                return ResourceManager.GetString("btn_text_refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        internal static string btn_text_retry {
            get {
                return ResourceManager.GetString("btn_text_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string copy_last_week {
            get {
                return ResourceManager.GetString("copy_last_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a com.ineco.android.master.
        /// </summary>
        internal static string credenciales {
            get {
                return ResourceManager.GetString("credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una nueva versión de la aplicación.
        /// </summary>
        internal static string dialog_approve_install {
            get {
                return ResourceManager.GetString("dialog_approve_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea aprobar la solicitud?.
        /// </summary>
        internal static string dialog_approve_message {
            get {
                return ResourceManager.GetString("dialog_approve_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene algunas solicitudes marcadas. ¿Desea aprobarlas?.
        /// </summary>
        internal static string dialog_approve_messages {
            get {
                return ResourceManager.GetString("dialog_approve_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        internal static string dialog_approve_positive {
            get {
                return ResourceManager.GetString("dialog_approve_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalar.
        /// </summary>
        internal static string dialog_approve_positive_install {
            get {
                return ResourceManager.GetString("dialog_approve_positive_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca mínimo 4 carácteres.
        /// </summary>
        internal static string dialog_approve_search {
            get {
                return ResourceManager.GetString("dialog_approve_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar solicitud.
        /// </summary>
        internal static string dialog_approve_title {
            get {
                return ResourceManager.GetString("dialog_approve_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string dialog_approve_title_search {
            get {
                return ResourceManager.GetString("dialog_approve_title_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso correcto..
        /// </summary>
        internal static string dialog_correct_access {
            get {
                return ResourceManager.GetString("dialog_correct_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las horas imputadas en un día superan el máximo permitido.
        /// </summary>
        internal static string dialog_pend_save {
            get {
                return ResourceManager.GetString("dialog_pend_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea rechazar la solicitud?.
        /// </summary>
        internal static string dialog_refuse_message {
            get {
                return ResourceManager.GetString("dialog_refuse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene algunas solicitudes marcadas. ¿Desea rechazarlas?.
        /// </summary>
        internal static string dialog_refuse_messages {
            get {
                return ResourceManager.GetString("dialog_refuse_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        internal static string dialog_refuse_positive {
            get {
                return ResourceManager.GetString("dialog_refuse_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        internal static string dialog_refuse_reason {
            get {
                return ResourceManager.GetString("dialog_refuse_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe informar el motivo de rechazo.
        /// </summary>
        internal static string dialog_refuse_text {
            get {
                return ResourceManager.GetString("dialog_refuse_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar solicitud.
        /// </summary>
        internal static string dialog_refuse_title {
            get {
                return ResourceManager.GetString("dialog_refuse_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string dialog_search_positive {
            get {
                return ResourceManager.GetString("dialog_search_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar menú.
        /// </summary>
        internal static string drawer_close {
            get {
                return ResourceManager.GetString("drawer_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir menú.
        /// </summary>
        internal static string drawer_open {
            get {
                return ResourceManager.GetString("drawer_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay elementos en la bandeja de entrada.
        /// </summary>
        internal static string empty_categories {
            get {
                return ResourceManager.GetString("empty_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen solicitudes.
        /// </summary>
        internal static string empty_messages {
            get {
                return ResourceManager.GetString("empty_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error en la aplicación.
        /// </summary>
        internal static string exception_message_generic {
            get {
                return ResourceManager.GetString("exception_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos. Por favor inténtelo de nuevo..
        /// </summary>
        internal static string exception_message_login {
            get {
                return ResourceManager.GetString("exception_message_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible obtener datos de la solicitud. Compruebe su conexión a internet.
        /// </summary>
        internal static string exception_message_message_not_found {
            get {
                return ResourceManager.GetString("exception_message_message_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La conexión a internet parece estar desactivada.
        /// </summary>
        internal static string exception_message_no_connection {
            get {
                return ResourceManager.GetString("exception_message_no_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible obtener datos de usuario. Compruebe su conexión a internet.
        /// </summary>
        internal static string exception_message_user_not_found {
            get {
                return ResourceManager.GetString("exception_message_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string hint_text_email {
            get {
                return ResourceManager.GetString("hint_text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiqueta.
        /// </summary>
        internal static string hint_text_label {
            get {
                return ResourceManager.GetString("hint_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string hint_text_password {
            get {
                return ResourceManager.GetString("hint_text_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string hint_text_user {
            get {
                return ResourceManager.GetString("hint_text_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info InetApp.
        /// </summary>
        internal static string info_inetapp {
            get {
                return ResourceManager.GetString("info_inetapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App.
        /// </summary>
        internal static string keyapp {
            get {
                return ResourceManager.GetString("keyapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a categoryName.
        /// </summary>
        internal static string keycategoryname {
            get {
                return ResourceManager.GetString("keycategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a i6KvvUNxz7.
        /// </summary>
        internal static string keyfullnombreuser {
            get {
                return ResourceManager.GetString("keyfullnombreuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IzSkiR0nDz.
        /// </summary>
        internal static string keyfullpassuser {
            get {
                return ResourceManager.GetString("keyfullpassuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreUser.
        /// </summary>
        internal static string keynombreuser {
            get {
                return ResourceManager.GetString("keynombreuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreUsuarioFull.
        /// </summary>
        internal static string keynombreuserfull {
            get {
                return ResourceManager.GetString("keynombreuserfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idApplication.
        /// </summary>
        internal static string keynotidapplication {
            get {
                return ResourceManager.GetString("keynotidapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idSolicitud.
        /// </summary>
        internal static string keynotidsolicitud {
            get {
                return ResourceManager.GetString("keynotidsolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a notiExterna.
        /// </summary>
        internal static string keynoTipoMsg {
            get {
                return ResourceManager.GetString("keynoTipoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a message.
        /// </summary>
        internal static string keynotmessage {
            get {
                return ResourceManager.GetString("keynotmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a numSolicitudes.
        /// </summary>
        internal static string keynotnumsolicitudes {
            get {
                return ResourceManager.GetString("keynotnumsolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a title.
        /// </summary>
        internal static string keynottitle {
            get {
                return ResourceManager.GetString("keynottitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a url.
        /// </summary>
        internal static string keynoUrlMsg {
            get {
                return ResourceManager.GetString("keynoUrlMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a isPermission.
        /// </summary>
        internal static string keyPermission {
            get {
                return ResourceManager.GetString("keyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sol.
        /// </summary>
        internal static string keysol {
            get {
                return ResourceManager.GetString("keysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dispone de permisos para acceder a este contenido.
        /// </summary>
        internal static string no_permissions {
            get {
                return ResourceManager.GetString("no_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo abrir la puerta, inténtelo de nuevo más tarde..
        /// </summary>
        internal static string notification_text {
            get {
                return ResourceManager.GetString("notification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo abrir la puerta..
        /// </summary>
        internal static string notification_title {
            get {
                return ResourceManager.GetString("notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña vacia. Por favor inténtelo de nuevo.
        /// </summary>
        internal static string password_empty_error {
            get {
                return ResourceManager.GetString("password_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas pendientes.
        /// </summary>
        internal static string pending_hours {
            get {
                return ResourceManager.GetString("pending_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TokenRegsitration.
        /// </summary>
        internal static string registratiotoken {
            get {
                return ResourceManager.GetString("registratiotoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos.
        /// </summary>
        internal static string seleccionartodos {
            get {
                return ResourceManager.GetString("seleccionartodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13164573839.
        /// </summary>
        internal static string sender_id {
            get {
                return ResourceManager.GetString("sender_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista no accesible.
        /// </summary>
        internal static string string_content_description {
            get {
                return ResourceManager.GetString("string_content_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TODAS.
        /// </summary>
        internal static string tab_text_all {
            get {
                return ResourceManager.GetString("tab_text_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MARCADAS.
        /// </summary>
        internal static string tab_text_marked {
            get {
                return ResourceManager.GetString("tab_text_marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROYECTO.
        /// </summary>
        internal static string table_project {
            get {
                return ResourceManager.GetString("table_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P. GESTIÓN.
        /// </summary>
        internal static string table_project_management {
            get {
                return ResourceManager.GetString("table_project_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -SELECCIONA PROYECTO-.
        /// </summary>
        internal static string text_combo {
            get {
                return ResourceManager.GetString("text_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dedicación contrato: %1$s.
        /// </summary>
        internal static string text_dedication {
            get {
                return ResourceManager.GetString("text_dedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DETALLES.
        /// </summary>
        internal static string text_details {
            get {
                return ResourceManager.GetString("text_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes activar o desactivar las distintas bandejas de solicitudes a través del menú principal:.
        /// </summary>
        internal static string text_info {
            get {
                return ResourceManager.GetString("text_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string text_label {
            get {
                return ResourceManager.GetString("text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Situe el código QR en el centro del lector para verificar el acceso:.
        /// </summary>
        internal static string text_lector {
            get {
                return ResourceManager.GetString("text_lector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas son las Bandejas de solicitudes pendientes disponibles actualmente:.
        /// </summary>
        internal static string text_options {
            get {
                return ResourceManager.GetString("text_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el ID o Título del proyecto.
        /// </summary>
        internal static string text_proyect_search {
            get {
                return ResourceManager.GetString("text_proyect_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmado.
        /// </summary>
        internal static string text_signed {
            get {
                return ResourceManager.GetString("text_signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validado.
        /// </summary>
        internal static string text_validated {
            get {
                return ResourceManager.GetString("text_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semana %1$s.
        /// </summary>
        internal static string text_week {
            get {
                return ResourceManager.GetString("text_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud aprobada correctamente.
        /// </summary>
        internal static string toast_approve_message {
            get {
                return ResourceManager.GetString("toast_approve_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible aprobar la solicitud.
        /// </summary>
        internal static string toast_approve_message_error {
            get {
                return ResourceManager.GetString("toast_approve_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes aprobadas correctamente.
        /// </summary>
        internal static string toast_approve_messages {
            get {
                return ResourceManager.GetString("toast_approve_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones guardadas correctamente.
        /// </summary>
        internal static string toast_approve_options {
            get {
                return ResourceManager.GetString("toast_approve_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar iconos.
        /// </summary>
        internal static string toast_error_icons {
            get {
                return ResourceManager.GetString("toast_error_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos mensajes no han sido aprobados.
        /// </summary>
        internal static string toast_not_all_messages_approved {
            get {
                return ResourceManager.GetString("toast_not_all_messages_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos mensajes no han sido rechazados.
        /// </summary>
        internal static string toast_not_all_messages_refused {
            get {
                return ResourceManager.GetString("toast_not_all_messages_refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud rechazada correctamente.
        /// </summary>
        internal static string toast_refuse_message {
            get {
                return ResourceManager.GetString("toast_refuse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible rechazar la solicitud.
        /// </summary>
        internal static string toast_refuse_message_error {
            get {
                return ResourceManager.GetString("toast_refuse_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes rechazadas correctamente.
        /// </summary>
        internal static string toast_refuse_messages {
            get {
                return ResourceManager.GetString("toast_refuse_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parte guardado correctamente.
        /// </summary>
        internal static string toast_save_parts {
            get {
                return ResourceManager.GetString("toast_save_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parte firmado correctamente.
        /// </summary>
        internal static string toast_sign_parts {
            get {
                return ResourceManager.GetString("toast_sign_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas totales.
        /// </summary>
        internal static string total_hours {
            get {
                return ResourceManager.GetString("total_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toral horas semana: %1$s.
        /// </summary>
        internal static string total_week_hours {
            get {
                return ResourceManager.GetString("total_week_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ineco.com/.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario vacio. Por favor inténtelo de nuevo.
        /// </summary>
        internal static string username_empty_error {
            get {
                return ResourceManager.GetString("username_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión InetApp Android:.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ÚLTIMA ACTUALIZACIÓN: %1$s.
        /// </summary>
        internal static string view_text_last_updated {
            get {
                return ResourceManager.GetString("view_text_last_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar ahora.
        /// </summary>
        internal static string view_text_update_now {
            get {
                return ResourceManager.GetString("view_text_update_now", resourceCulture);
            }
        }
    }
}
